# Generated by Django 3.2.9 on 2023-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_anoncurl_centralhardwareurl_newsurl_photourl_videourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(upload_to='employee/'),
        ),
    ]
