# Generated by Django 3.2.9 on 2023-01-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20230121_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='photourl',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='videourl',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
