# Generated by Django 3.2.9 on 2023-01-22 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_yoshlargsoidyangiliklar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyurl',
            name='url',
        ),
        migrations.AddField(
            model_name='employee',
            name='division_of_responsibility',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='short_bio',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
