# Generated by Django 3.2.9 on 2023-01-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20230122_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoshlargsOidYangiliklar',
        ),
        migrations.AlterField(
            model_name='openbudgetfiles',
            name='categoryName',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='OpenBudgetNames',
        ),
    ]
