# Generated by Django 3.2.18 on 2023-04-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20230122_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openbudgetfiles',
            name='categoryName',
        ),
    ]
