# Generated by Django 3.2.18 on 2023-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_openbudgetfiles_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openbudgetfiles',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
