# Generated by Django 3.2.18 on 2023-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_openbudgetfiles_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photourl',
            name='image',
        ),
        migrations.AddField(
            model_name='photourl',
            name='image1',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='photourl',
            name='image2',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='photourl',
            name='image3',
            field=models.FileField(blank=True, upload_to='photos/'),
        ),
    ]
