# Generated by Django 3.2.18 on 2023-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20230404_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalFilesUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='journalImages/')),
                ('files', models.FileField(upload_to='journalFiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
